import type { Metadata } from "next";
// import { GeistSans } from "geist/font/sans";
import Header from "@/components/Header";
import { cn } from "@/lib/utils";
import "./globals.css";

import { Instrument_Sans, Space_Grotesk } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const instrumentSans = Instrument_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-instrument-sans",
});

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-space-grotesk",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "antialiased max-w-5xl lg:mx-auto",
          instrumentSans.variable,
          spaceGrotesk.variable,
        )}
      >
        <Header />
        <main className="flex-auto min-w-0 mt-6 flex flex-col px-2 md:px-0">
          {children}
        </main>
      </body>
    </html>
  );
}
