import type { Metadata } from "next";
// import { GeistSans } from "geist/font/sans";
import Header from "@/components/Header";
import { cn } from "@/lib/utils";
import "./globals.css";

import { Figtree, Space_Grotesk } from "next/font/google";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const spaceGrotesk = Space_Grotesk({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-space-grotesk",
});

// const instrumentSans = Instrument_Sans({
//   subsets: ["latin"],
//   weight: ["400", "500", "600", "700"],
//   variable: "--font-instrument-sans",
// });

const figtree = Figtree({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
  variable: "--font-figtree",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${cn(
          "antialiased max-w-3xl lg:mx-auto",
          // instrumentSans.className,
          spaceGrotesk.className,
          figtree.variable,
          // "bg-[#F4F4F5]"
        )}`}
      >
        <Header />
        <main className="flex-auto min-w-0 mt-6 flex flex-col px-2 md:px-0">
          {children}
        </main>
        <footer className="py-20 text-center text-gray-500 text-sm">
          <p>
            &copy; {new Date().getFullYear()}{" "}
            <a
              href="
https://harrybaines.co.uk"
              className="underline"
            >
              Harry Baines
            </a>
          </p>
        </footer>
      </body>
    </html >
  );
}
